language: java

jdk:
  - oraclejdk7
  - openjdk7

install:
  - ./gradlew -PossrhUsername=none -PossrhPassword=none --stacktrace jars

script:
  - ./gradlew -PossrhUsername=none -PossrhPassword=none --stacktrace check
